print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "D:/GitHub/TheGame/TheGame/Assets/3DModels/AllAssets.mb"`)
{		
	file -o "D:/GitHub/TheGame/TheGame/Assets/3DModels/AllAssets.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "D:/GitHub/TheGame/TheGame/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "D:/GitHub/TheGame/TheGame/Temp/CommandPipe";

$donepipeKill = `fopen "D:/GitHub/TheGame/TheGame/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
